apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: databases-secrets
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: databases-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /dev/dev-k8s/postgres/superuser-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /dev/dev-k8s/postgres/superuser-password
