clusterName: dev-k8s
cluster:
  dnsDomain: cluster.local
envSecretName: aws-lbc-credentials

# Set from variable by `templatefile` call in aws_lbc.tf
region: ${region}
# this value changes every time base_infrastructure is re-created
# Set from base_infrastructure output by `templatefile` call in aws_lbc.tf
vpcId: ${vpcId}
