apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets
            name: eso-reader-aws-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: eso-reader-aws-credentials
            key: secret-access-key
