apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-lbc-credentials
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: aws-lbc-credentials
    creationPolicy: Owner
  data:
    - secretKey: key_id
      remoteRef:
        key: /dev/dev-k8s/aws-lbc-user-access-key-id
    - secretKey: access_key
      remoteRef:
        key: /dev/dev-k8s/aws-lbc-user-secret-access-key

