apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: cert-manager-secrets
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: /dev/dev-k8s/cert-manager-route-53-access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: /dev/dev-k8s/cert-manager-route-53-secret-access-key

