controller:                                                                                                                                                                                  
    env:          
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-secret
            key: key_id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:                                                                                                                                                                             
          secretKeyRef:
            name: aws-secret                                                                                                                                                                   
            key: access_key
